In [1]:
import numpy as np

In [2]:
from genome_file import encodeAdj, read_genome

In [3]:
from dcj_comp import dcj_dist

In [4]:
# def neighbor(A, num):
#     index = np.where(A == num)[0][0]
#     if index % 2 == 0:
#         index += 1
#     else:
#         index -= 1
#     return A[index]

# def findPath(A, B, num, visited, path):
#     if num in visited:
#         return True
#     if num == -1:
#         return False
    
#     visited.append(num)
#     nb = neighbor(B, num)
#     path.append((num, nb))
#     return findPath(B, A, nb, visited, path)

# def dcj_dist(A, B):
#     visited = []
#     cycle, oddp = 0, 0
    
#     for i in range(1, len(A) - 1):
#         if A[i] in visited:
#             continue
#         path = []
#         if findPath(A, B, A[i], visited, path):
#             cycle += 1
#             continue
            
#         nb = neighbor(A, A[i])
#         if nb not in visited:
#             findPath(A, B, nb, visited, path)
#         path = [(nb, A[i])] + path
#         if len(path) % 2 == 0:
#             oddp += 1
        
#     return cycle, oddp, (len(A) - 2)//2 - (cycle + oddp // 2)

In [5]:
genes = read_genome()

In [6]:
for g in genes:
    if len(g) == 1:
        print(g, len(g[0]))

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]] 20
[[1, 13, 14, 15, 16, 17, 18, -9, -8, -7, -6, -5, -4, -3, -2, -12, -11, -10, 19, 20]] 20
[[-11, -10, 19, 14, 15, 16, 17, 18, -9, -8, -7, -6, -5, -4, -3, -2, -12, 1, 13, 20]] 20
[[-11, -10, 19, 14, 15, 16, 17, 18, -9, -8, -7, -6, -5, -4, -3, -2, -12, 1, 13, 20]] 20
[[-11, -10, 19, 14, 15, 16, 17, 18, 7, 8, 9, -6, -5, -4, -3, -2, -12, 1, 13, 20]] 20
[[-5, -2, -12, -19, 10, -17, 11, -6, -20, 3, -14, -9, 13, -4, 1, -8, -7, 15, 16, 18]] 20
[[-5, -2, -12, -19, 10, -9, 13, -4, 1, -17, 11, -6, -20, 3, -14, -8, -7, 15, 16, 18]] 20
[[-5, -2, -12, -19, 10, 14, -3, 20, 6, -11, 17, -1, 4, -13, 9, -8, -7, 15, 16, 18]] 20
[[8, -9, 13, -10, 3, 20, 14, 2, 19, -17, 11, 5, -18, -16, -4, 1, 12, 7, -15, -6]] 20


In [13]:
encodeAdj([1,2,3])

array([-1,  0,  1,  2,  3,  4,  5, -2], dtype=int32)

In [9]:
from gene_mat import trans_rev

In [10]:
np.matmul(np.array([[1,2,3,-4]]), trans_rev(4, 2,4,2,1))

array([[ 1,  2, -3,  4]])

In [11]:
np.matmul(np.array([[1,2,3,-4]]), trans_rev(4, 1,3,2,1))

array([[ 1, -4, -2, -3]])

In [15]:
dcj_dist([1,2,3], [1,2,3])

[-1  0  1  2  3  4  5 -2] [-1  0  1  2  3  4  5 -2]


(4, 0, 0)