In [1]:
import numpy as np

In [2]:
from genome_file import encodeAdj, read_genome

In [2]:
from dcj_comp import dcj_dist

In [5]:
genes = read_genome()

In [13]:
encodeAdj([1,2,3])

array([-1,  0,  1,  2,  3,  4,  5, -2], dtype=int32)

In [9]:
from gene_mat import trans_rev

In [10]:
np.matmul(np.array([[1,2,3,-4]]), trans_rev(4, 2,4,2,1))

array([[ 1,  2, -3,  4]])

In [11]:
np.matmul(np.array([[1,2,3,-4]]), trans_rev(4, 1,3,2,1))

array([[ 1, -4, -2, -3]])

In [4]:
dcj_dist([1,2,3,-4], [ 1, -4, -2, -3])

(3, 0, 2)