In [1]:
import torch
import numpy as np

from gene_graph_dataset import G2GraphDataset

In [2]:
from torch_geometric.utils import to_scipy_sparse_matrix

In [3]:
g2g_data = G2GraphDataset('g2gdataset', 10, 3)

In [4]:
g2g_data

G2GraphDataset(30000)

In [5]:
g = g2g_data[0]

In [6]:
g.pos_edge_label_index

tensor([[13, 12, 17, 16, 19, 18,  9,  8, 15, 14,  1,  0, 11, 10,  3,  2,  6,  7,
          5],
        [12, 17, 16, 19, 18,  9,  8, 15, 14,  1,  0, 11, 10,  3,  2,  6,  7,  5,
          4]])

In [7]:
from torch_geometric.utils import negative_sampling

In [8]:
negative_sampling(g.pos_edge_label_index, g.x.size(0), num_neg_samples = 300).shape

torch.Size([2, 300])

In [9]:
mg = to_scipy_sparse_matrix(negative_sampling(g.pos_edge_label_index, g.x.size(0))).toarray()

In [10]:
mg.sum()

19.0

In [11]:
mg.sum(1)

array([0., 1., 0., 1., 1., 1., 2., 0., 1., 0., 0., 2., 0., 1., 3., 1., 1.,
       1., 2., 1.], dtype=float32)

In [12]:
mg.sum(0)

array([2., 2., 1., 3., 2., 0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0., 0.,
       1., 1., 0.], dtype=float32)