In [1]:
import numpy as np

In [53]:
tmp = np.array([range(1,11)])

In [54]:
tmp

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [55]:
fac = np.zeros((10,10), dtype = np.int32)

In [56]:
np.fill_diagonal(fac, 1)

In [57]:
tmp.shape

(1, 10)

In [58]:
tmp.T.shape

(10, 1)

In [59]:
np.matmul(tmp, fac)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [60]:
fac

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [26]:
fac[3:5, 4:2:-1]

array([[0, 1],
       [1, 0]], dtype=int32)

In [68]:
fac[3,4] = 0

In [69]:
fac[4,3] = 0

In [61]:
np.matmul(tmp, fac)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [70]:
fac[3,3] = 1

In [71]:
fac[4,4] = 1

In [72]:
fac

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [73]:
fac[3,7] = 1
fac[7,3] = 1

In [75]:
fac[3,3] = 0
fac[7,7] = 0

In [82]:
fac[4,8]=1
fac[8,3] = 1
fac[4,4] = 0
fac[8,8]=0
fac[5,4] = fac[6,5] = fac[7,6] = 1
fac[5,5] = fac[6,6] = fac[7,7] = 0

In [84]:
fac[7,3] = 0

In [85]:
fac

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [86]:
np.matmul(tmp, fac)

array([[ 1,  2,  3,  9,  6,  7,  8,  4,  5, 10]])

In [77]:
np.matmul(tmp, fac)

array([[ 1,  2,  3,  8,  5,  6,  7,  4,  9, 10]])

In [36]:
test = np.zeros((3,3), dtype = np.int32)

In [37]:
test

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [39]:
np.fill_diagonal(test, 1)

In [40]:
test

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [49]:
tmp = np.array([[1,-1,-1]] * 3)

In [50]:
tmp

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [ 1, -1, -1]])

In [51]:
np.matmul(test, tmp)

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [ 1, -1, -1]])

In [87]:
test = np.array([[1,2,3]])
mat = np.zeros((3,4), dtype = np.int32)

In [89]:
np.fill_diagonal(mat, 1)
mat[0,3] = 1

In [90]:
np.matmul(test,mat)

array([[1, 2, 3, 1]])

In [91]:
mat

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int32)

In [96]:
np.matmul(test, mat[:, [0,2]])

array([[1, 3]])

In [99]:
np.diag([1] * 10)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [100]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [109]:
t = np.diag(np.repeat(1,10))

In [110]:
t

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [111]:
t[:, 2:5] = t[:, 4:1:-1]

In [112]:
t

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [121]:
def revs(size, p1, p2):
    if p1 > p2:
        p1, p2 = p2, p1
    res = np.diag(np.repeat(1,size))
    res[:, p1:p2] = np.fliplr(res[:, p1:p2]) * -1
    return res

In [122]:
fac = revs(10, 0,10)

In [123]:
tmp

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [124]:
np.matmul(tmp, fac)

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1]])

In [128]:
import random
for _ in range(100):
    p1 = random.randint(0,10)
    p2 = random.randint(0,10)
    tmp = np.matmul(tmp, revs(10, p1, p2))
    print(tmp)

[[ 1  2 -6 -5 -4 -3  7  8  9 10]]
[[ 1  2 -6 -5 -7  3  4  8  9 10]]
[[ 1 -3  7  5  6 -2  4  8  9 10]]
[[ 1 -3 -8 -4  2 -6 -5 -7  9 10]]
[[  1  -3 -10  -9   7   5   6  -2   4   8]]
[[  1  -3 -10   2  -6  -5  -7   9   4   8]]
[[  1  -3 -10   2  -6  -5  -7   9  -4   8]]
[[  3  -1 -10   2  -6  -5  -7   9  -4   8]]
[[  3  -1 -10   5   6  -2  -7   9  -4   8]]
[[ 3 -1  2 -6 -5 10 -7  9 -4  8]]
[[  7 -10   5   6  -2   1  -3   9  -4   8]]
[[  7 -10   5   2  -6   1  -3   9  -4   8]]
[[ 7 -9  3 -1  6 -2 -5 10 -4  8]]
[[  7  -9   3  -1   6  -2   4 -10   5   8]]
[[  7  -9   3   1   6  -2   4 -10   5   8]]
[[  2  -6  -1  -3   9  -7   4 -10   5   8]]
[[  3   1   6  -2   9  -7   4 -10   5   8]]
[[-8 -5 10 -4  7 -9  2 -6 -1 -3]]
[[ -8   1   6  -2   9  -7   4 -10   5  -3]]
[[ -8   1   2  -6   9  -7   4 -10   5  -3]]
[[-8 -5 10 -4  7 -9  6 -2 -1 -3]]
[[ -7   4 -10   5   8  -9   6  -2  -1  -3]]
[[-7  4  9 -8 -5 10  6 -2 -1 -3]]
[[-7  4  9 -8 -5 10  6 -2  1 -3]]
[[-7  5  8 -9 -4 10  6 -2  1 -3]]
[[-5  7  8

In [135]:
def circle(size, p1, p2):
    if p1 > p2:
        p1, p2 = p2, p1
    res = np.diag(np.repeat(1,size))
    return res[:, np.r_[0:p1, p2:size]], res[:,np.r_[p1:p2, p1]]

In [136]:
np.r_[3:7, 3:]

array([3, 4, 5, 6, 0, 1, 2])

In [137]:
tmp = np.array([range(1,11)])
l,c = circle(10, 3,6)
np.matmul(tmp, l)

array([[ 1,  2,  3,  7,  8,  9, 10]])

In [138]:
np.matmul(tmp, c)

array([[4, 5, 6, 4]])

In [141]:
fac.shape

(10, 10)

In [142]:
l.shape

(10, 7)

In [143]:
c.shape

(10, 4)

In [146]:
def trans(size, p1, p2, p3, p4):
    p1,p2,p3,p4 = sorted([p1,p2,p3,p4])
    res = np.diag(np.repeat(1,size))
    return res[:, np.r_[0:p1, p3:p4, p2:p3, p1:p2, p4:size]]

In [145]:
sorted([1,3,2,4])

[1, 2, 3, 4]

In [149]:
np.matmul(tmp, trans(10, 3, 5, 5, 9))

array([[ 1,  2,  3,  6,  7,  8,  9,  4,  5, 10]])

In [161]:
import torch as th

In [162]:
device = th.device('cuda')

In [151]:
def trans_rev(size, p1, p2, p3, p4):
    p1, p2, p3, p4 = sorted([p1, p2, p3, p4])
    res = np.diag(np.repeat(1,size))
    res = res[:, np.r_[0:p1, p3:p4, p2:p3, p1:p2, p4:size]]
    end = p1 + p4 - p3 + p3 - p2
    res[:, p1:end] = np.fliplr(res[:, p1:end]) * -1
    return res

In [182]:
n = 200
tmp = np.array([range(1,n + 1)])
mat_list = []
for _ in range(20):
    p1,p2,p3,p4 = [random.randint(0,n) for _ in range(4)]
    mat_list.append(trans_rev(n, p1, p2, p3, p4))
tmp_tensor = th.tensor(tmp, dtype = th.float, device = device)
mat_tensor = th.tensor(mat_list, dtype = th.float, device = device)
test = th.matmul(tmp_tensor, mat_tensor)

In [183]:
tmp_tensor

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
          25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
          37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
          49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
          61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
          73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
          85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
          97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
         109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
         121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
         133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
         145., 146., 147., 1

In [194]:
for x in test[:3]:
    print(x)

tensor([[   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,
           11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,
           21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,   30.,
           31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,   40.,
           41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,   50.,
           51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,   60.,
           61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,   70.,
           71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
           81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
           91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99., -106.,
         -105., -104., -103., -122., -121., -120., -119., -118., -117., -116.,
         -115., -114., -113., -112., -111., -110., -109., -108., -107.,  100.,
          101.,  102.,  123.,  124.,  125.,  126.,  

In [192]:
res = th.matmul(test, mat_tensor)

In [195]:
test[0]

tensor([[   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,
           11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,
           21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,   30.,
           31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,   40.,
           41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,   50.,
           51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,   60.,
           61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,   70.,
           71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
           81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
           91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99., -106.,
         -105., -104., -103., -122., -121., -120., -119., -118., -117., -116.,
         -115., -114., -113., -112., -111., -110., -109., -108., -107.,  100.,
          101.,  102.,  123.,  124.,  125.,  126.,  

In [193]:
for x in res[:3]:
    print(x)

tensor([[   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,
           11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,
           21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,   30.,
           31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,   40.,
           41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,   50.,
           51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,   60.,
           61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,   70.,
           71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
           81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
           91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,  120.,
          121.,  122.,  103., -102., -101., -100.,  107.,  108.,  109.,  110.,
          111.,  112.,  113.,  114.,  115.,  116.,  117.,  118.,  119., -106.,
         -105., -104.,  123.,  124.,  125.,  126.,  

In [212]:
n = 200
tmp = np.array([range(1,n + 1)])
mat_list = []
for _ in range(20):
    p1,p2,p3,p4 = [random.randint(0,n) for _ in range(4)]
    mat_list.append(revs(n, p1, p2))
tmp_tensor = th.tensor(tmp, dtype = th.float, device = device)
mat_tensor = th.tensor(mat_list, dtype = th.float, device = device)
test = th.matmul(tmp_tensor, mat_tensor)

In [213]:
test[0]

tensor([[   1., -139., -138., -137., -136., -135., -134., -133., -132., -131.,
         -130., -129., -128., -127., -126., -125., -124., -123., -122., -121.,
         -120., -119., -118., -117., -116., -115., -114., -113., -112., -111.,
         -110., -109., -108., -107., -106., -105., -104., -103., -102., -101.,
         -100.,  -99.,  -98.,  -97.,  -96.,  -95.,  -94.,  -93.,  -92.,  -91.,
          -90.,  -89.,  -88.,  -87.,  -86.,  -85.,  -84.,  -83.,  -82.,  -81.,
          -80.,  -79.,  -78.,  -77.,  -76.,  -75.,  -74.,  -73.,  -72.,  -71.,
          -70.,  -69.,  -68.,  -67.,  -66.,  -65.,  -64.,  -63.,  -62.,  -61.,
          -60.,  -59.,  -58.,  -57.,  -56.,  -55.,  -54.,  -53.,  -52.,  -51.,
          -50.,  -49.,  -48.,  -47.,  -46.,  -45.,  -44.,  -43.,  -42.,  -41.,
          -40.,  -39.,  -38.,  -37.,  -36.,  -35.,  -34.,  -33.,  -32.,  -31.,
          -30.,  -29.,  -28.,  -27.,  -26.,  -25.,  -24.,  -23.,  -22.,  -21.,
          -20.,  -19.,  -18.,  -17.,  -16.,  -15.,  

In [214]:
res = th.matmul(test, mat_tensor)

In [215]:
res[16]

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
          25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
          37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
          49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
          61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
          73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
          85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
          97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
         109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
         121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
         133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
         145., 146., 147., 1

In [216]:
test.shape

torch.Size([20, 1, 200])

In [217]:
reshape_test = th.reshape(test, (-1, 1, 1, 200))

In [218]:
reshape_test.shape

torch.Size([20, 1, 1, 200])

In [219]:
res = th.matmul(reshape_test, mat_tensor)

In [220]:
res.shape

torch.Size([20, 20, 1, 200])

In [229]:
res[1,1]

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
          25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
          37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
          49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
          61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
          73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
          85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
          97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
         109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
         121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
         133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
         145., 146., 147., 1

In [236]:
for i in range(10):
    x = th.reshape(res, (-1, 1,1,200))
    res = th.matmul(x, mat_tensor)
    print(res.shape)

torch.Size([400, 20, 1, 200])


RuntimeError: CUDA out of memory. Tried to allocate 23.84 GiB (GPU 0; 11.92 GiB total capacity; 138.05 MiB already allocated; 8.70 GiB free; 328.00 MiB reserved in total by PyTorch)

In [234]:
x[42]

tensor([[[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
           12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
           23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
           34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
           45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
           56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
           67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
           78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
           89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
          100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
          111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
          122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
          133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
          14

In [245]:
import math
import time

In [ ]:
n = 6
count = 2**n*math.factorial(n)
for _ in range(1):
    num = []
    genes_5 = []
    g_5 = [list(range(1, n + 1))]
    test = th.tensor(g_5, dtype = th.float, device = device)
    num.append((1,-1))
    genes_5.append(g_5)
    for i in range(10000000):
        p1,p2,p3,p4 = [random.randint(0,n) for _ in range(4)]
        op_list = []
        for _ in range(2000):
            op_type = random.randint(0,2)
            if op_type == 0:
                trans_mat = trans_rev(n, p1, p2, p3, p4)
            elif op_type == 1:
                trans_mat = trans(n, p1, p2, p3, p4)
            else:
                trans_mat = revs(n, p1, p2)
            op_list.append(trans_mat)
            
        
        mat_tensor = th.tensor(op_list, dtype = th.float, device = device)
        test = th.matmul(test, mat_tensor)
        
        g_res = test.cpu().numpy().astype(dtype=np.int32).tolist()
        for g_5 in g_res:
            if g_5 not in genes_5:
                genes_5.append(g_5)
        l = len(genes_5)
        if l > num[-1][0]:
            num.append((l, i))
            if l%100 == 0 or i % 100 == 0: 
                print(time.ctime(), num[-1])
        if l >= count:
            break
    print(num[-1])

Mon Nov  1 23:42:39 2021 (4, 0)
Mon Nov  1 23:47:58 2021 (44740, 100)
Mon Nov  1 23:52:54 2021 (46000, 174)
